name: Проверка

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Установить uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.14"

      - name: Установить зависимости
        run: uv sync

      - name: Линтер
        run: uv run ruff check .

      - name: Тесты
        run: uv run pytest
